- id: '1606768564570'
  alias: Christmas Tree Power
  description: Turn on Christmas tree lights at sunset
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: 4dc56595b3b2bc0ddeef704e73b6148a
    entity_id: switch.christmas_tree
    domain: switch
  - delay: 06:00
  - type: turn_off
    device_id: 4dc56595b3b2bc0ddeef704e73b6148a
    entity_id: switch.christmas_tree
    domain: switch
  mode: single
- id: '1607044077710'
  alias: Start Homekit
  description: Starts HomeKit service when z wave network is ready
  trigger:
  - platform: event
    event_type: zwave.network_ready
  - platform: event
    event_type: zwave.network_complete
  - platform: event
    event_type: zwave.network_complete_some_dead
  action:
  - service: homekit.start
  mode: single
- id: '1607459606775'
  alias: Lock Front Door Delay
  description: Will lock the front door after x minutes.
  trigger:
  - platform: device
    device_id: 33c84b4be5a0e6d7c799cc53558c7b52
    domain: lock
    entity_id: lock.front_door
    type: unlocked
  condition:
  - condition: numeric_state
    entity_id: input_number.lock_after_delay
    above: '0'
  action:
  - delay: 00:{{ states("input_number.lock_after_delay") | int }}
  - service: lock.lock
    data: {}
    entity_id: lock.front_door
  mode: single
- id: '1607557633859'
  alias: Kitched LEDs at Sunset
  description: Turns on kitchen accessory lighting at sunset and turns off at midnight.
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: 842024f401af9288a2e7751ab9f50038
    entity_id: light.eb50d4ab8e43dd4e9944re
    domain: light
    brightness_pct: 80
  - type: turn_on
    device_id: 5b19356c467c69cee68b6ba3681cc026
    entity_id: light.bloom
    domain: light
    brightness_pct: 80
  - delay: 06:00
  - type: turn_off
    device_id: 842024f401af9288a2e7751ab9f50038
    entity_id: light.eb50d4ab8e43dd4e9944re
    domain: light
  - type: turn_off
    device_id: 5b19356c467c69cee68b6ba3681cc026
    entity_id: light.bloom
    domain: light
  mode: single
- id: '1607655474196'
  alias: Door Notifications
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: binary_sensor.back_door
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: binary_sensor.garage_entry_door
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_jordans_iphone
    data:
      message: '{{ trigger.to_state.attributes.friendly_name }} was {{ ''opened''
        if trigger.to_state.state else ''closed'' }}'
  mode: single
- id: '1607741444008'
  alias: Notify Me on Plex Viewer change
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.plex_rossmediacenter
  condition: []
  action:
  - service: notify.mobile_app_jordans_iphone
    data:
      message: Plex viewers changed to {{ trigger.to_state.state }}
  mode: single
