---
#
#  _              _ _   _                
# | |            | | | (_)               
# | |__   ___  __| | |_ _ _ __ ___   ___ 
# | '_ \ / _ \/ _` | __| | '_ ` _ \ / _ \
# | |_) |  __/ (_| | |_| | | | | | |  __/
# |_.__/ \___|\__,_|\__|_|_| |_| |_|\___|
#

- alias: "Bedtime: report"
  trigger:
    - platform: time
      at: input_datetime.bedtime_report
  condition: "{{ is_state('binary_sensor.bedtime_report', 'on') }}"
  action:
    - service: notify.mobile_app_jordans_iphone
      data:
        title: "Bedtime Status Report"
        message: >
          {% if is_state('binary_sensor.bedtime_lights_on', 'on') %}
          {{ 'Lights:\n  ' -}}
          {{ expand('group.bedtime_lights') | selectattr('state','eq','on') | list | map(attribute='name') | join('\n  ') -}}
          {{ '\n' -}}
          {% endif %}{% if is_state('binary_sensor.window_status', 'on') %}{{ 'Windows:\n  ' -}}
          {{ expand('group.all_windows') | selectattr('state','eq','on') | list | map(attribute='name') | join('\n  ') -}}
          {{ '\n' -}}
          {% endif %}{% if is_state('cover.garage', 'open') %}Garage: {{ states('cover.garage') }}{{ '\n' -}}
          {% endif %}{% if is_state('lock.front_door', 'unlocked') %}Front door: {{ states('lock.front_door') }}{{ '\n' -}}
          {% endif %}
        data:
          push:
            category: bedtime

- alias: "Bedtime: activate"
  trigger:
    - platform: time
      at: input_datetime.bedtime_delayed
  condition: "{{ is_state('binary_sensor.bedtime_report', 'on') }}"
  action:
    - service: scene.turn_on
      entity_id: scene.good_night
    - service: input_datetime.set_datetime
      entity_id: input_datetime.bedtime_delayed
      data_template:
        datetime: input_datetime.bedtime
      
- alias: "Bedtime: good night"
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: GOOD_NIGHT
  action:
    service: scene.turn_on
    entity_id: scene.good_night

- alias: "Bedtime: delay"
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: GOOD_NIGHT_DELAY
  action:
    service: input_datetime.set_datetime
    entity_id: input_datetime.bedtime_delayed
    data_template:
      datetime: >
        {{ (as_timestamp(input_datetime.bedtime) + as_timestamp(input_datetime.bedtime_delay_amount)) | timestamp_custom("%H:%M") }}
