---
#
#  _              _ _   _                
# | |            | | | (_)               
# | |__   ___  __| | |_ _ _ __ ___   ___ 
# | '_ \ / _ \/ _` | __| | '_ ` _ \ / _ \
# | |_) |  __/ (_| | |_| | | | | | |  __/
# |_.__/ \___|\__,_|\__|_|_| |_| |_|\___|
#

- alias: "Bedtime: report"
  trigger:
    - platform: time
      at: "{{ states('input_boolean.bedtime') }}"
  condition: "{{ is_state('bedtime_report', 'on') }}"
  action:
    - service: notify.mobile_app_jordans_iphone
      data:
        title: "Check this out!"
        message: "Test!"
        data:
          push:
            category: "bedtime"
          action_data: # Anything passed in action_data will get echoed back to Home Assistant.
            entity_id: light.test
            my_custom_data: foo_bar