---
#
#  _              _ _   _                
# | |            | | | (_)               
# | |__   ___  __| | |_ _ _ __ ___   ___ 
# | '_ \ / _ \/ _` | __| | '_ ` _ \ / _ \
# | |_) |  __/ (_| | |_| | | | | | |  __/
# |_.__/ \___|\__,_|\__|_|_| |_| |_|\___|
#

- alias: "Bedtime: report"
  trigger:
    - platform: time
      at: input_datetime.bedtime
  condition: "{{ is_state('bedtime_report', 'on') }}"
  action:
    - service: notify.mobile_app_jordans_iphone
      data:
        title: "Bedtime Status Report"
        message: >
          Lights:
          {{ {% if is_state('light.living_room_lamp', 'on') %}
          - Living Room Lamp
          {% endif %} }}
          {{ {% if is_state('light.shatterdome_lamp', 'on') %}
          - Shatterdome Lamp
          {% endif %} }}
          Garage: {{ states('cover.garage') }}
          Front Door: {{ states('lock.front_door') }}
        data:
          push:
            category: BEDTIME

- alias: "Bedtime: good night"
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: BEDTIME
  action:
    service: scene.turn_on
    entity_id: scene.good_night