#
#  _     _
# | |   (_)
# | |__  _ _ __   __ _ _ __ _   _   ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | | / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| | \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, | |___/\___|_| |_|___/\___/|_|  |___/
#                            __/ |
#                           |___/
#                   

- platform: template
  sensors:
    window_status:
      friendly_name: "Window Status"
      device_class: window
      value_template: "{{ expand('group.all_windows') | selectattr('state','eq','on') | list | count > 0 }}"

    door_status:
      friendly_name: "Door Status"
      device_class: door
      value_template: "{{ expand('group.all_doors') | selectattr('state','eq','on') | list | count > 0 }}"

    media_status:
      friendly_name: "Media Player Status"
      value_template: >
        {{ expand('group.all_media_players')
        | rejectattr('state','eq','idle')
        | rejectattr('state','eq','off')
        | rejectattr('state','eq','unavailable')
        | list | count > 0 }}

    bedtime_report:
      friendly_name: "Bedtime Report"
      value_template: >
        {{ is_state('light.shatterdome_light', 'on') or
          is_state('binary_sensor.bedtime_lights_on', 'on') or
          is_state('binary_sensor.window_status', 'on') or 
          is_state('cover.garage', 'open') }}
      
    bedtime_lights_on:
      friendly_name: "Bedtime Lights On"
      value_template: >
        {{ expand('group.bedtime_lights')
        | selectattr('state','eq','on')
        | list | count > 0 }}