# binary
#   ____________________ _______    _________________ __________  _________
#  /   _____/\_   _____/ \      \  /   _____/\_____  \\______   \/   _____/ 
#  \_____  \  |    __)_  /   |   \ \_____  \  /   |   \|       _/\_____  \  
#  /        \ |        \/    |    \/        \/    |    \    |   \/        \ 
# /_______  //_______  /\____|__  /_______  /\_______  /____|_  /_______  / 
#         \/         \/         \/        \/         \/       \/        \/ 
#

- platform: template
  sensors:
    window_status:
      friendly_name: "Window Status"
      entity_id:
        - binary_sensor.front_room_window_1
        - binary_sensor.front_room_window_2
        - binary_sensor.living_room_window_1
        - binary_sensor.living_room_window_2
        - binary_sensor.living_room_window_3
        - binary_sensor.guest_bedroom_window
        - binary_sensor.kitchen_window
      device_class: window
      value_template: "{{ expand('group.all_windows') | selectattr('state','eq','on') | list | count > 0 }}"

    door_status:
      friendly_name: "Door Status"
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.back_door
        - binary_sensor.garage_entry_door
      device_class: door
      value_template: "{{ expand('group.all_doors') | selectattr('state','eq','on') | list | count > 0 }}"

- platform: group
  name: All Doors
  entities:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_entry_door

- platform: group
  name: All Windows
  entities:
    - binary_sensor.front_room_window_1
    - binary_sensor.front_room_window_2
    - binary_sensor.living_room_window_1
    - binary_sensor.living_room_window_2
    - binary_sensor.living_room_window_3
    - binary_sensor.guest_bedroom_window
    - binary_sensor.kitchen_window