#
#  _     _
# | |   (_)
# | |__  _ _ __   __ _ _ __ _   _   ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | | / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| | \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, | |___/\___|_| |_|___/\___/|_|  |___/
#                            __/ |
#                           |___/
#                   

- platform: template
  sensors:
    window_status:
      friendly_name: "Window Status"
      entity_id:
        - binary_sensor.front_room_window_1
        - binary_sensor.front_room_window_2
        - binary_sensor.living_room_window_1
        - binary_sensor.living_room_window_2
        - binary_sensor.living_room_window_3
        - binary_sensor.guest_bedroom_window
        - binary_sensor.kitchen_window
      device_class: window
      value_template: "{{ expand('group.all_windows') | selectattr('state','eq','on') | list | count > 0 }}"

    door_status:
      friendly_name: "Door Status"
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.back_door
        - binary_sensor.garage_entry_door
      device_class: door
      value_template: "{{ expand('group.all_doors') | selectattr('state','eq','on') | list | count > 0 }}"

    media_status:
      friendly_name: "Media Player Status"
      entity_id:
        - media_player.spotify_lilboarder32
        - media_player.spotify_lilboarder32
        - media_player.shatterdome_speaker
        - media_player.onkybro
        - media_player.nursery_speaker
        - media_player.master_bedroom_speaker
        - media_player.living_room_tv
        - media_player.kitchen_display
      value_template: >
        {{ expand('group.all_media_players')
        | rejectattr('state','eq','idle')
        | rejectattr('state','eq','off')
        | rejectattr('state','eq','unavailable')
        | list | count > 0 }}