#
#  _ _       _     _       
# | (_)     | |   | |      
# | |_  __ _| |__ | |_ ___ 
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#       __/ |              
#      |___/               
# 

- platform: group
  name: Living Room Lamp
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2
    - light.living_room_lamp_3

- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2
    - light.living_room_lamp_3
    - light.tv_lightstrip

- platform: group
  name: Kitchen Lights
  entities:
    - light.bloom
    - light.cabinet_lightstrip

- platform: group
  name: Shatterdome Lamp
  entities:
    - light.gaming_lamp_1
    - light.gaming_lamp_2
    - light.gaming_lamp_3