#
#                     _ _       
#                    | (_)      
#  _ __ ___   ___  __| |_  __ _ 
# | '_ ` _ \ / _ \/ _` | |/ _` |
# | | | | | |  __/ (_| | | (_| |
# |_| |_| |_|\___|\__,_|_|\__,_|
#

- platform: group
  name: All Media Players
  entities:
    - media_player.spotify_lilboarder32
    - media_player.shatterdome_speaker
    - media_player.onkybro
    - media_player.nursery_speaker
    - media_player.master_bedroom_speaker
    - media_player.living_room_tv
    - media_player.kitchen_display
