#
#   ____________________ _______    _________________ __________  _________
#  /   _____/\_   _____/ \      \  /   _____/\_____  \\______   \/   _____/ 
#  \_____  \  |    __)_  /   |   \ \_____  \  /   |   \|       _/\_____  \  
#  /        \ |        \/    |    \/        \/    |    \    |   \/        \ 
# /_______  //_______  /\____|__  /_______  /\_______  /____|_  /_______  / 
#         \/         \/         \/        \/         \/       \/        \/ 
#

- platform: template
  sensors:
    pool_temp:
      friendly_name: "Pool Temp"
      value_template: "{{ state_attr('climate.pool', 'current_temperature') }}"
      unit_of_measurement: F
      
    spa_temp:
      friendly_name: "Spa Temp"
      value_template: "{{ state_attr('climate.spa', 'current_temperature') }}"
      unit_of_measurement: F